services:
  backend:
    image: ppratahk/backend:latest
    container_name: backend
    restart: always
    ports:
      - '5000:5000'
    environment:
      DB_HOST: scoreboard-public.c1sk2imgwsr1.us-west-1.rds.amazonaws.com
      DB_USER: admin
      DB_PASSWORD: qwerty123
      DB_NAME: scoreboard
    networks:
      - scoreboard-network

  frontend:
    image: ppratahk/frontend:latest
    container_name: frontend
    restart: always
    ports:
      - '3000:3000'
    environment:
      REACT_APP_API_BASE_URL: http://54.219.114.228:5000
    depends_on:
      - backend
    networks:
      - scoreboard-network

networks:
  scoreboard-network:
    external: true

volumes:
  db_data: